version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: queue-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: queue-frontend
    ports:
      - "3000:80"  # React served by Nginx on port 80 -> mapped to host:3000
    depends_on:
      - backend
    restart: unless-stopped
